# bug_fixer

analyze_startup_failure_task:
  description: >
    The backend could not start. Error was:
    {test_result}

    Read both 'Output/models.py' and 'Output/app.py' to determine what might have caused the failure

    Your job:
    - Read Output/app.py and Output/models.py using FileReaderTool
    - Identify the code sections that make the app not executable
    - Write a fix plan

  expected_output: >
    Markdown file with problems and how to fix each
  agent: bug_fixer


analyze_failed_requests_task:
  description: >
    Here is the test result from the TestCrew:
    {test_result}

    Read both 'Output/models.py' and 'Output/app.py' to determine what might have caused the failure.

    For each failed request:
      - Match it to the code sections in models.py or app.py.
      - Determine if the issue is due to missing fields, wrong data types, missing routes, or logic bugs.
      - Propose how to fix it.
    You are not fixing the bug yet. Your job is only to isolate the issue and create a plan.

  expected_output: >
    Your final output must be a Markdown file titled "Bug Fix Plan",
    listing each ❌ failed request, the likely root cause, and what changes are needed
    (which file and what code section to fix).

    Format example:
    ---
    ❌ PUT /teams/1
    Cause: Missing field "city" not handled in PUT route
    Fix: Add support for 'city' in PUT handler in app.py

    ❌ POST /players
    Cause: Model 'Player' missing 'position' field
    Fix: Add 'position = db.String' to Player class in models.py
    ---

  agent: bug_fixer

fix_code_task:
  description: >
    Use the bug fix plan from your context to modify the files 'Output/models.py' and/or 'Output/app.py'.
    You must:
      - Read both files first using the FileReaderTool
      - Apply only the fixes that are clearly defined in the fix plan
      - Preserve all existing code not related to the bug
      - Use FileWriterTool to write your fixed version back to the same path

  expected_output: >
    Your final answer must confirm:
    - What file(s) were changed
    - What sections were modified
    - The final confirmation of write success (e.g. "models.py updated successfully.")

  agent: bug_fixer
  output_file: Output/fix_summary.md
